main_layout = QHBoxLayout(self)

left_widget = QWidget()
left_layout = QVBoxLayout(left_widget)
left_layout.setContentsMargins(0, 0, 0, 0)

form_layout = QFormLayout()

self.batch_mode_checkbox = QCheckBox("Batch Mode")
self.batch_mode_checkbox.toggled.connect(self.toggle_mode)
form_layout.addRow(self.batch_mode_checkbox)

self.single_url_input = QLineEdit()
self.single_url_input.setPlaceholderText("Paste URL here...")

self.batch_url_input = QTextEdit()
self.batch_url_input.setPlaceholderText("Paste URLs here (one per line)...")
self.batch_url_input.setFixedHeight(100)
self.batch_url_input.setLineWrapMode(QTextEdit.LineWrapMode.NoWrap)
self.batch_url_input.setVisible(False)

self.btn_fetch_data = QPushButton("Fetch Data")
self.btn_fetch_data.setFixedWidth(80)
self.btn_fetch_data.clicked.connect(lambda: self.fetch_data())

url_container = QVBoxLayout()
url_container.addWidget(self.single_url_input)
url_container.addWidget(self.batch_url_input)

input_row_layout = QHBoxLayout()
input_row_layout.addLayout(url_container)
input_row_layout.addWidget(self.btn_fetch_data)

form_layout.addRow("URL:", input_row_layout)

self.out_input = QLineEdit(self.config["out_dir"])
self.btn_browse_out = QPushButton("...")
self.btn_browse_out.setFixedWidth(30)
self.btn_browse_out.clicked.connect(lambda: self.browse_folder(self.out_input))
out_layout = QHBoxLayout()
out_layout.addWidget(self.out_input)
out_layout.addWidget(self.btn_browse_out)
form_layout.addRow("Output Path:", out_layout)

self.temp_input = QLineEdit(self.config["temp_dir"])
self.btn_browse_temp = QPushButton("...")
self.btn_browse_temp.setFixedWidth(30)
self.btn_browse_temp.clicked.connect(lambda: self.browse_folder(self.temp_input))
temp_layout = QHBoxLayout()
temp_layout.addWidget(self.temp_input)
temp_layout.addWidget(self.btn_browse_temp)
form_layout.addRow("Temp Path:", temp_layout)

self.cover_input = QLineEdit(self.config["cover_dir"])
self.btn_browse_cover = QPushButton("...")
self.btn_browse_cover.setFixedWidth(30)
self.btn_browse_cover.clicked.connect(lambda: self.browse_folder(self.cover_input))
cover_layout = QHBoxLayout()
cover_layout.addWidget(self.cover_input)
cover_layout.addWidget(self.btn_browse_cover)
form_layout.addRow("Cover Path:", cover_layout)

self.num_threads_input = QSpinBox()
self.num_threads_input.setRange(1, 128)
self.num_threads_input.setValue(int(self.config.get("max_threads", 4)))
self.num_threads_input.setFixedWidth(100)
form_layout.addRow("Max Threads:", self.num_threads_input)

self.lyrics_checkbox = QCheckBox()
self.lyrics_checkbox.setChecked(self.config["download_lyrics"])
self.lyrics_checkbox.setFixedWidth(100)
form_layout.addRow("Download Lyrics:", self.lyrics_checkbox)

self.artist_albums_checkbox = QCheckBox()
self.artist_albums_checkbox.setChecked(self.config["artist_album_only"])
container_layout = QHBoxLayout()
container_layout.addWidget(QLabel("[ARTISTS] Download ONLY albums:"))
container_layout.addWidget(self.artist_albums_checkbox)
container_layout.addStretch()
form_layout.addRow(container_layout)

left_layout.addLayout(form_layout)

self.start_btn = QPushButton("Start Download")
self.start_btn.setMinimumHeight(40)
self.start_btn.clicked.connect(self.start_process)
left_layout.addWidget(self.start_btn)

self.console_label = QLabel("Console Output:")
left_layout.addWidget(self.console_label)
self.console = QTextEdit()
self.console.setReadOnly(True)
self.console.setStyleSheet("background-color: #222; color: #EEE; font-family: Consolas, monospace;")
left_layout.addWidget(self.console)

right_widget = QWidget()
right_widget.setFixedWidth(320)
right_layout = QVBoxLayout(right_widget)
right_layout.setContentsMargins(10, 0, 0, 0)

self.cover_label = QLabel()
self.cover_label.setFixedSize(300, 300)
self.cover_label.setStyleSheet("background-color: #333; border: 1px solid #555;")
self.cover_label.setAlignment(Qt.AlignCenter)
self.cover_label.setText("No Cover")
right_layout.addWidget(self.cover_label)

self.info_console = QTextEdit()
self.info_console.setReadOnly(True)
self.info_console.setStyleSheet("background-color: #222; color: #EEE; font-family: Consolas, monospace;")
self.info_console.setFixedWidth(300)
right_layout.addWidget(self.info_console, 1)
right_layout.addStretch()

main_layout.addWidget(left_widget, 1) 
main_layout.addWidget(right_widget, 0)